In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [3]:
train_transaction = pd.read_csv('data/train_transaction.csv')
train_identity = pd.read_csv('data/train_identity.csv')
test_transaction = pd.read_csv('data/test_transaction.csv')
test_identity = pd.read_csv('data/test_identity.csv')

In [26]:
train_transaction.head(5)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
train_identity.head(5)

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [28]:
train_transaction.describe()

,TransactionID,isFraud,TransactionDT,TransactionAmt,card1,card2,card3,card5,addr1,addr2,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
count,5.905400e+05,590540.000000,5.905400e+05,590540.000000,590540.000000,581607.000000,588975.000000,586281.000000,524834.000000,524834.000000,...,82351.000000,82351.000000,82351.000000,82351.000000,82351.000000,82351.00000,82351.000000,82351.000000,82351.000000,82351.000000
mean,3.282270e+06,0.034990,7.372311e+06,135.027176,9898.734658,362.555488,153.194925,199.278897,290.733794,86.800630,...,0.775874,721.741883,1375.783644,1014.622782,9.807015,59.16455,28.530903,55.352422,151.160542,100.700882
std,1.704744e+05,0.183755,4.617224e+06,239.162522,4901.170153,157.793246,11.336444,41.244453,101.741072,2.690623,...,4.727971,6217.223583,11169.275702,7955.735482,243.861391,387.62948,274.576920,668.486833,1095.034387,814.946722
min,2.987000e+06,0.000000,8.640000e+04,0.251000,1000.000000,100.000000,100.000000,100.000000,100.000000,10.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,3.134635e+06,0.000000,3.027058e+06,43.321000,6019.000000,214.000000,150.000000,166.000000,204.000000,87.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,3.282270e+06,0.000000,7.306528e+06,68.769000,9678.000000,361.000000,150.000000,226.000000,299.000000,87.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,3.429904e+06,0.000000,1.124662e+07,125.000000,14184.000000,512.000000,150.000000,226.000000,330.000000,87.000000,...,0.000000,0.000000,25.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
max,3.577539e+06,1.000000,1.581113e+07,31937.391000,18396.000000,600.000000,231.000000,237.000000,540.000000,102.000000,...,55.000000,160000.000000,160000.000000,160000.000000,55125.000000,55125.00000,55125.000000,104060.000000,104060.000000,104060.000000

In [29]:
train_identity.describe()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_17,id_18,id_19,id_20,id_21,id_22,id_24,id_25,id_26,id_32
count,1.442330e+05,144233.000000,140872.000000,66324.000000,66324.000000,136865.000000,136865.000000,5155.000000,5155.000000,74926.000000,...,139369.000000,45113.000000,139318.000000,139261.000000,5159.000000,5169.000000,4747.000000,5132.000000,5163.000000,77586.000000
mean,3.236329e+06,-10.170502,174716.584708,0.060189,-0.058938,1.615585,-6.698710,13.285354,-38.600388,0.091023,...,189.451377,14.237337,353.128174,403.882666,368.269820,16.002708,12.800927,329.608924,149.070308,26.508597
std,1.788496e+05,14.347949,159651.816856,0.598231,0.701015,5.249856,16.491104,11.384207,26.084899,0.983842,...,30.375360,1.561302,141.095343,152.160327,198.847038,6.897665,2.372447,97.461089,32.101995,3.737502
min,2.987004e+06,-100.000000,1.000000,-13.000000,-28.000000,-72.000000,-100.000000,-46.000000,-100.000000,-36.000000,...,100.000000,10.000000,100.000000,100.000000,100.000000,10.000000,11.000000,100.000000,100.000000,0.000000
25%,3.077142e+06,-10.000000,67992.000000,0.000000,0.000000,0.000000,-6.000000,5.000000,-48.000000,0.000000,...,166.000000,13.000000,266.000000,256.000000,252.000000,14.000000,11.000000,321.000000,119.000000,24.000000
50%,3.198818e+06,-5.000000,125800.500000,0.000000,0.000000,0.000000,0.000000,14.000000,-34.000000,0.000000,...,166.000000,15.000000,341.000000,472.000000,252.000000,14.000000,11.000000,321.000000,149.000000,24.000000
75%,3.392923e+06,-5.000000,228749.000000,0.000000,0.000000,1.000000,0.000000,22.000000,-23.000000,0.000000,...,225.000000,15.000000,427.000000,533.000000,486.500000,14.000000,15.000000,371.000000,169.000000,32.000000
max,3.577534e+06,0.000000,999595.000000,10.000000,0.000000,52.000000,0.000000,61.000000,0.000000,25.000000,...,229.000000,29.000000,671.000000,661.000000,854.000000,44.000000,26.000000,548.000000,216.000000,32.000000

Since both the data frames have transaction ID's, we can concatenate both the tables into a single table.

In [4]:
df_train = pd.merge(left = train_transaction, right = train_identity, on = 'TransactionID', how = 'left')
df_test = pd.merge(left = test_transaction, right = test_identity, on = 'TransactionID', how = 'left')

In [5]:
missing_values = df_train.isna().sum().reset_index(name = 'count')

In [6]:
cols = list(df_train.columns)
print('Column name', "-----------------", 'Null values')
columns = 0 
for col in cols:
    if df_train[col].isna().sum() > 0: 
        columns += 1 
        print(f'{col}: ----------------- {df_train[col].isna().sum()}')
print(f'Total number of columns with missing value = {columns}')

Column name ----------------- Null values
card2: ----------------- 8933
card3: ----------------- 1565
card4: ----------------- 1577
card5: ----------------- 4259
card6: ----------------- 1571
addr1: ----------------- 65706
addr2: ----------------- 65706
dist1: ----------------- 352271
dist2: ----------------- 552913
P_emaildomain: ----------------- 94456
R_emaildomain: ----------------- 453249
D1: ----------------- 1269
D2: ----------------- 280797
D3: ----------------- 262878
D4: ----------------- 168922
D5: ----------------- 309841
D6: ----------------- 517353
D7: ----------------- 551623
D8: ----------------- 515614
D9: ----------------- 515614
D10: ----------------- 76022
D11: ----------------- 279287
D12: ----------------- 525823
D13: ----------------- 528588
D14: ----------------- 528353
D15: ----------------- 89113
M1: ----------------- 271100
M2: ----------------- 271100
M3: ----------------- 271100
M4: ----------------- 281444
M5: ----------------- 350482
M6: ----------------- 169360
M7: ----------------- 346265
M8: ----------------- 346252
M9: ----------------- 346252
V1: ----------------- 279287
V2: ----------------- 279287
V3: ----------------- 279287
V4: ----------------- 279287
V5: ----------------- 279287
V6: ----------------- 279287
V7: ----------------- 279287
V8: ----------------- 279287
V9: ----------------- 279287
V10: ----------------- 279287
V11: ----------------- 279287
V12: ----------------- 76073
V13: ----------------- 76073
V14: ----------------- 76073
V15: ----------------- 76073
V16: ----------------- 76073
V17: ----------------- 76073
V18: ----------------- 76073
V19: ----------------- 76073
V20: ----------------- 76073
V21: ----------------- 76073
V22: ----------------- 76073
V23: ----------------- 76073
V24: ----------------- 76073
V25: ----------------- 76073
V26: ----------------- 76073
V27: ----------------- 76073
V28: ----------------- 76073
V29: ----------------- 76073
V30: ----------------- 76073
V31: ----------------- 76073
V32: ----------------- 76073
V33: ----------------- 76073
V34: ----------------- 76073
V35: ----------------- 168969
V36: ----------------- 168969
V37: ----------------- 168969
V38: ----------------- 168969
V39: ----------------- 168969
V40: ----------------- 168969
V41: ----------------- 168969
V42: ----------------- 168969
V43: ----------------- 168969
V44: ----------------- 168969
V45: ----------------- 168969
V46: ----------------- 168969
V47: ----------------- 168969
V48: ----------------- 168969
V49: ----------------- 168969
V50: ----------------- 168969
V51: ----------------- 168969
V52: ----------------- 168969
V53: ----------------- 77096
V54: ----------------- 77096
V55: ----------------- 77096
V56: ----------------- 77096
V57: ----------------- 77096
V58: ----------------- 77096
V59: ----------------- 77096
V60: ----------------- 77096
V61: ----------------- 77096
V62: ----------------- 77096
V63: ----------------- 77096
V64: ----------------- 77096
V65: ----------------- 77096
V66: ----------------- 77096
V67: ----------------- 77096
V68: ----------------- 77096
V69: ----------------- 77096
V70: ----------------- 77096
V71: ----------------- 77096
V72: ----------------- 77096
V73: ----------------- 77096
V74: ----------------- 77096
V75: ----------------- 89164
V76: ----------------- 89164
V77: ----------------- 89164
V78: ----------------- 89164
V79: ----------------- 89164
V80: ----------------- 89164
V81: ----------------- 89164
V82: ----------------- 89164
V83: ----------------- 89164
V84: ----------------- 89164
V85: ----------------- 89164
V86: ----------------- 89164
V87: ----------------- 89164
V88: ----------------- 89164
V89: ----------------- 89164
V90: ----------------- 89164
V91: ----------------- 89164
V92: ----------------- 89164
V93: ----------------- 89164
V94: ----------------- 89164
V95: ----------------- 314
V96: ----------------- 314
V97: ----------------- 314
V98: ----------------- 314
V99: ----------------- 314
V100: ----------------- 314
V101: ----------------- 314
V102: ----------------- 314
V103: ----------------- 314
V104: ----------------- 314
V105: ----------------- 314
V106: ----------------- 314
V107: ----------------- 314
V108: ----------------- 314
V109: ----------------- 314
V110: ----------------- 314
V111: ----------------- 314
V112: ----------------- 314
V113: ----------------- 314
V114: ----------------- 314
V115: ----------------- 314
V116: ----------------- 314
V117: ----------------- 314
V118: ----------------- 314
V119: ----------------- 314
V120: ----------------- 314
V121: ----------------- 314
V122: ----------------- 314
V123: ----------------- 314
V124: ----------------- 314
V125: ----------------- 314
V126: ----------------- 314
V127: ----------------- 314
V128: ----------------- 314
V129: ----------------- 314
V130: ----------------- 314
V131: ----------------- 314
V132: ----------------- 314
V133: ----------------- 314
V134: ----------------- 314
V135: ----------------- 314
V136: ----------------- 314
V137: ----------------- 314
V138: ----------------- 508595
V139: ----------------- 508595
V140: ----------------- 508595
V141: ----------------- 508595
V142: ----------------- 508595
V143: ----------------- 508589
V144: ----------------- 508589
V145: ----------------- 508589
V146: ----------------- 508595
V147: ----------------- 508595
V148: ----------------- 508595
V149: ----------------- 508595
V150: ----------------- 508589
V151: ----------------- 508589
V152: ----------------- 508589
V153: ----------------- 508595
V154: ----------------- 508595
V155: ----------------- 508595
V156: ----------------- 508595
V157: ----------------- 508595
V158: ----------------- 508595
V159: ----------------- 508589
V160: ----------------- 508589
V161: ----------------- 508595
V162: ----------------- 508595
V163: ----------------- 508595
V164: ----------------- 508589
V165: ----------------- 508589
V166: ----------------- 508589
V167: ----------------- 450909
V168: ----------------- 450909
V169: ----------------- 450721
V170: ----------------- 450721
V171: ----------------- 450721
V172: ----------------- 450909
V173: ----------------- 450909
V174: ----------------- 450721
V175: ----------------- 450721
V176: ----------------- 450909
V177: ----------------- 450909
V178: ----------------- 450909
V179: ----------------- 450909
V180: ----------------- 450721
V181: ----------------- 450909
V182: ----------------- 450909
V183: ----------------- 450909
V184: ----------------- 450721
V185: ----------------- 450721
V186: ----------------- 450909
V187: ----------------- 450909
V188: ----------------- 450721
V189: ----------------- 450721
V190: ----------------- 450909
V191: ----------------- 450909
V192: ----------------- 450909
V193: ----------------- 450909
V194: ----------------- 450721
V195: ----------------- 450721
V196: ----------------- 450909
V197: ----------------- 450721
V198: ----------------- 450721
V199: ----------------- 450909
V200: ----------------- 450721
V201: ----------------- 450721
V202: ----------------- 450909
V203: ----------------- 450909
V204: ----------------- 450909
V205: ----------------- 450909
V206: ----------------- 450909
V207: ----------------- 450909
V208: ----------------- 450721
V209: ----------------- 450721
V210: ----------------- 450721
V211: ----------------- 450909
V212: ----------------- 450909
V213: ----------------- 450909
V214: ----------------- 450909
V215: ----------------- 450909
V216: ----------------- 450909
V217: ----------------- 460110
V218: ----------------- 460110
V219: ----------------- 460110
V220: ----------------- 449124
V221: ----------------- 449124
V222: ----------------- 449124
V223: ----------------- 460110
V224: ----------------- 460110
V225: ----------------- 460110
V226: ----------------- 460110
V227: ----------------- 449124
V228: ----------------- 460110
V229: ----------------- 460110
V230: ----------------- 460110
V231: ----------------- 460110
V232: ----------------- 460110
V233: ----------------- 460110
V234: ----------------- 449124
V235: ----------------- 460110
V236: ----------------- 460110
V237: ----------------- 460110
V238: ----------------- 449124
V239: ----------------- 449124
V240: ----------------- 460110
V241: ----------------- 460110
V242: ----------------- 460110
V243: ----------------- 460110
V244: ----------------- 460110
V245: ----------------- 449124
V246: ----------------- 460110
V247: ----------------- 460110
V248: ----------------- 460110
V249: ----------------- 460110
V250: ----------------- 449124
V251: ----------------- 449124
V252: ----------------- 460110
V253: ----------------- 460110
V254: ----------------- 460110
V255: ----------------- 449124
V256: ----------------- 449124
V257: ----------------- 460110
V258: ----------------- 460110
V259: ----------------- 449124
V260: ----------------- 460110
V261: ----------------- 460110
V262: ----------------- 460110
V263: ----------------- 460110
V264: ----------------- 460110
V265: ----------------- 460110
V266: ----------------- 460110
V267: ----------------- 460110
V268: ----------------- 460110
V269: ----------------- 460110
V270: ----------------- 449124
V271: ----------------- 449124
V272: ----------------- 449124
V273: ----------------- 460110
V274: ----------------- 460110
V275: ----------------- 460110
V276: ----------------- 460110
V277: ----------------- 460110
V278: ----------------- 460110
V279: ----------------- 12
V280: ----------------- 12
V281: ----------------- 1269
V282: ----------------- 1269
V283: ----------------- 1269
V284: ----------------- 12
V285: ----------------- 12
V286: ----------------- 12
V287: ----------------- 12
V288: ----------------- 1269
V289: ----------------- 1269
V290: ----------------- 12
V291: ----------------- 12
V292: ----------------- 12
V293: ----------------- 12
V294: ----------------- 12
V295: ----------------- 12
V296: ----------------- 1269
V297: ----------------- 12
V298: ----------------- 12
V299: ----------------- 12
V300: ----------------- 1269
V301: ----------------- 1269
V302: ----------------- 12
V303: ----------------- 12
V304: ----------------- 12
V305: ----------------- 12
V306: ----------------- 12
V307: ----------------- 12
V308: ----------------- 12
V309: ----------------- 12
V310: ----------------- 12
V311: ----------------- 12
V312: ----------------- 12
V313: ----------------- 1269
V314: ----------------- 1269
V315: ----------------- 1269
V316: ----------------- 12
V317: ----------------- 12
V318: ----------------- 12
V319: ----------------- 12
V320: ----------------- 12
V321: ----------------- 12
V322: ----------------- 508189
V323: ----------------- 508189
V324: ----------------- 508189
V325: ----------------- 508189
V326: ----------------- 508189
V327: ----------------- 508189
V328: ----------------- 508189
V329: ----------------- 508189
V330: ----------------- 508189
V331: ----------------- 508189
V332: ----------------- 508189
V333: ----------------- 508189
V334: ----------------- 508189
V335: ----------------- 508189
V336: ----------------- 508189
V337: ----------------- 508189
V338: ----------------- 508189
V339: ----------------- 508189
id_01: ----------------- 446307
id_02: ----------------- 449668
id_03: ----------------- 524216
id_04: ----------------- 524216
id_05: ----------------- 453675
id_06: ----------------- 453675
id_07: ----------------- 585385
id_08: ----------------- 585385
id_09: ----------------- 515614
id_10: ----------------- 515614
id_11: ----------------- 449562
id_12: ----------------- 446307
id_13: ----------------- 463220
id_14: ----------------- 510496
id_15: ----------------- 449555
id_16: ----------------- 461200
id_17: ----------------- 451171
id_18: ----------------- 545427
id_19: ----------------- 451222
id_20: ----------------- 451279
id_21: ----------------- 585381
id_22: ----------------- 585371
id_23: ----------------- 585371
id_24: ----------------- 585793
id_25: ----------------- 585408
id_26: ----------------- 585377
id_27: ----------------- 585371
id_28: ----------------- 449562
id_29: ----------------- 449562
id_30: ----------------- 512975
id_31: ----------------- 450258
id_32: ----------------- 512954
id_33: ----------------- 517251
id_34: ----------------- 512735
id_35: ----------------- 449555
id_36: ----------------- 449555
id_37: ----------------- 449555
id_38: ----------------- 449555
DeviceType: ----------------- 449730
DeviceInfo: ----------------- 471874
Total number of columns with missing value = 414

We see a lot of columns have missing values with 412 columns in total having missing values. Now let us see how many columns have a high degree of missing values, to the point where imputation of any sort might not be precise and may lead to compromising the data quality.

In [7]:
high_missing_values = {}
for col in cols: 
    if df_train[col].isna().sum() > 0:
        prop = round(df_train[col].isna().sum()/len(df_train), 3)
        if prop > 0.5:
            print(f'{col} --------------- {prop}') 
            high_missing_values[col] = prop

dist1 --------------- 0.597
dist2 --------------- 0.936
R_emaildomain --------------- 0.768
D5 --------------- 0.525
D6 --------------- 0.876
D7 --------------- 0.934
D8 --------------- 0.873
D9 --------------- 0.873
D12 --------------- 0.89
D13 --------------- 0.895
D14 --------------- 0.895
M5 --------------- 0.593
M7 --------------- 0.586
M8 --------------- 0.586
M9 --------------- 0.586
V138 --------------- 0.861
V139 --------------- 0.861
V140 --------------- 0.861
V141 --------------- 0.861
V142 --------------- 0.861
V143 --------------- 0.861
V144 --------------- 0.861
V145 --------------- 0.861
V146 --------------- 0.861
V147 --------------- 0.861
V148 --------------- 0.861
V149 --------------- 0.861
V150 --------------- 0.861
V151 --------------- 0.861
V152 --------------- 0.861
V153 --------------- 0.861
V154 --------------- 0.861
V155 --------------- 0.861
V156 --------------- 0.861
V157 --------------- 0.861
V158 --------------- 0.861
V159 --------------- 0.861
V160 --------------- 0.861
V161 --------------- 0.861
V162 --------------- 0.861
V163 --------------- 0.861
V164 --------------- 0.861
V165 --------------- 0.861
V166 --------------- 0.861
V167 --------------- 0.764
V168 --------------- 0.764
V169 --------------- 0.763
V170 --------------- 0.763
V171 --------------- 0.763
V172 --------------- 0.764
V173 --------------- 0.764
V174 --------------- 0.763
V175 --------------- 0.763
V176 --------------- 0.764
V177 --------------- 0.764
V178 --------------- 0.764
V179 --------------- 0.764
V180 --------------- 0.763
V181 --------------- 0.764
V182 --------------- 0.764
V183 --------------- 0.764
V184 --------------- 0.763
V185 --------------- 0.763
V186 --------------- 0.764
V187 --------------- 0.764
V188 --------------- 0.763
V189 --------------- 0.763
V190 --------------- 0.764
V191 --------------- 0.764
V192 --------------- 0.764
V193 --------------- 0.764
V194 --------------- 0.763
V195 --------------- 0.763
V196 --------------- 0.764
V197 --------------- 0.763
V198 --------------- 0.763
V199 --------------- 0.764
V200 --------------- 0.763
V201 --------------- 0.763
V202 --------------- 0.764
V203 --------------- 0.764
V204 --------------- 0.764
V205 --------------- 0.764
V206 --------------- 0.764
V207 --------------- 0.764
V208 --------------- 0.763
V209 --------------- 0.763
V210 --------------- 0.763
V211 --------------- 0.764
V212 --------------- 0.764
V213 --------------- 0.764
V214 --------------- 0.764
V215 --------------- 0.764
V216 --------------- 0.764
V217 --------------- 0.779
V218 --------------- 0.779
V219 --------------- 0.779
V220 --------------- 0.761
V221 --------------- 0.761
V222 --------------- 0.761
V223 --------------- 0.779
V224 --------------- 0.779
V225 --------------- 0.779
V226 --------------- 0.779
V227 --------------- 0.761
V228 --------------- 0.779
V229 --------------- 0.779
V230 --------------- 0.779
V231 --------------- 0.779
V232 --------------- 0.779
V233 --------------- 0.779
V234 --------------- 0.761
V235 --------------- 0.779
V236 --------------- 0.779
V237 --------------- 0.779
V238 --------------- 0.761
V239 --------------- 0.761
V240 --------------- 0.779
V241 --------------- 0.779
V242 --------------- 0.779
V243 --------------- 0.779
V244 --------------- 0.779
V245 --------------- 0.761
V246 --------------- 0.779
V247 --------------- 0.779
V248 --------------- 0.779
V249 --------------- 0.779
V250 --------------- 0.761
V251 --------------- 0.761
V252 --------------- 0.779
V253 --------------- 0.779
V254 --------------- 0.779
V255 --------------- 0.761
V256 --------------- 0.761
V257 --------------- 0.779
V258 --------------- 0.779
V259 --------------- 0.761
V260 --------------- 0.779
V261 --------------- 0.779
V262 --------------- 0.779
V263 --------------- 0.779
V264 --------------- 0.779
V265 --------------- 0.779
V266 --------------- 0.779
V267 --------------- 0.779
V268 --------------- 0.779
V269 --------------- 0.779
V270 --------------- 0.761
V271 --------------- 0.761
V272 --------------- 0.761
V273 --------------- 0.779
V274 --------------- 0.779
V275 --------------- 0.779
V276 --------------- 0.779
V277 --------------- 0.779
V278 --------------- 0.779
V322 --------------- 0.861
V323 --------------- 0.861
V324 --------------- 0.861
V325 --------------- 0.861
V326 --------------- 0.861
V327 --------------- 0.861
V328 --------------- 0.861
V329 --------------- 0.861
V330 --------------- 0.861
V331 --------------- 0.861
V332 --------------- 0.861
V333 --------------- 0.861
V334 --------------- 0.861
V335 --------------- 0.861
V336 --------------- 0.861
V337 --------------- 0.861
V338 --------------- 0.861
V339 --------------- 0.861
id_01 --------------- 0.756
id_02 --------------- 0.761
id_03 --------------- 0.888
id_04 --------------- 0.888
id_05 --------------- 0.768
id_06 --------------- 0.768
id_07 --------------- 0.991
id_08 --------------- 0.991
id_09 --------------- 0.873
id_10 --------------- 0.873
id_11 --------------- 0.761
id_12 --------------- 0.756
id_13 --------------- 0.784
id_14 --------------- 0.864
id_15 --------------- 0.761
id_16 --------------- 0.781
id_17 --------------- 0.764
id_18 --------------- 0.924
id_19 --------------- 0.764
id_20 --------------- 0.764
id_21 --------------- 0.991
id_22 --------------- 0.991
id_23 --------------- 0.991
id_24 --------------- 0.992
id_25 --------------- 0.991
id_26 --------------- 0.991
id_27 --------------- 0.991
id_28 --------------- 0.761
id_29 --------------- 0.761
id_30 --------------- 0.869
id_31 --------------- 0.762
id_32 --------------- 0.869
id_33 --------------- 0.876
id_34 --------------- 0.868
id_35 --------------- 0.761
id_36 --------------- 0.761
id_37 --------------- 0.761
id_38 --------------- 0.761
DeviceType --------------- 0.762
DeviceInfo --------------- 0.799

Now, we see that certain columns have extremely high number of missing values with some even having extremely high proportions rising to about 99%. These columns can be removed as they provide no real information and at most serves as a source of noise in the system. I've chosen 80% as an arbitrary threshold for removing columns

In [8]:
cols_to_drop = []
for col in high_missing_values.keys():
    if high_missing_values[col] > 0.8:
        cols_to_drop.append(col)

In [9]:
df_train = df_train.drop(columns= cols_to_drop)
df_test = df_test.drop(columns = cols_to_drop)

In [42]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 360 entries, TransactionID to DeviceInfo
dtypes: float64(330), int64(4), object(26)
memory usage: 1.6+ GB

In [10]:
float_cols = df_test.select_dtypes(include = 'float64').columns
df_train[float_cols] = df_train[float_cols].astype('float32')
df_test[float_cols] = df_test[float_cols].astype('float32')

int_cols = df_test.select_dtypes(include = 'int64').columns
df_train[int_cols] = df_train[int_cols].astype('int32')
df_test[int_cols] = df_test[int_cols].astype('int32')

print(df_train.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 360 entries, TransactionID to DeviceInfo
dtypes: float32(330), int32(3), int64(1), object(26)
memory usage: 1.4 GB
None

In [51]:
df_train.to_pickle('data/df_train_cleaned.pkl')
df_test.to_pickle('data/df_test_cleaned.pkl')